"""Parse a coverage report and check whether code coverage satsifies a minimum threshold provided by the environment."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys

MIN_CODE_COVERAGE_ENV = "MIN_CODE_COVERAGE"


def parse_coverage_from_str(report: str) -> int:
    """Extracts the total coverage percentage from a coverage report string.

    Args:
        report (str): The coverage report as a multiline string.

    Returns:
        int: The total coverage percentage as an integer.

    Raises:
        ValueError: If the total coverage line cannot be found or parsed.
    """
    for line in report.splitlines():
        if line.strip().startswith("TOTAL"):
            match = re.search(r"(\d+)%$", line.strip())
            if match:
                return int(match.group(1))
            msg = "Coverage percentage not found in TOTAL line."
            raise ValueError(msg)

    msg = "TOTAL line not found in the report."
    raise ValueError(msg)


def main() -> None:  # noqa: D103
    parser = argparse.ArgumentParser(description="Check code coverage against a minimum threshold.")
    parser.add_argument(
        "coverage", help="Path to a coverage report generated by pytest with `--cov-report=term`."
    )
    parser.add_argument(
        "--fail-too-low",
        action="store_true",
        help="Exit with status 1 if coverage is below threshold.",
    )

    args = parser.parse_args()

    with Path(args.coverage).open() as f:
        report = f.read()

    try:
        coverage = parse_coverage_from_str(report)
    except Exception as e:  # noqa: BLE001
        print(f"Error reading coverage: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        min_coverage = float(os.environ.get(MIN_CODE_COVERAGE_ENV))
    except (TypeError, ValueError):
        print(
            f"Missing or invalid environment variable {MIN_CODE_COVERAGE_ENV} (must be float).",
            file=sys.stderr,
        )
        sys.exit(1)

    msg = (
        f"✅ Code coverage is **{coverage:.2f}%**. Great!"
        if coverage >= min_coverage
        else f"❌ Code coverage is **{coverage:.2f}%**, which is less than the required **{min_coverage}%**."
    )
    msg += f"\n\n```\n{report}\n```"
    print(msg)

    if args.fail_too_low and coverage < min_coverage:
        print("Code coverage is too low. Exiting with code 1 since --fail-too-low is set.")
        sys.exit(1)


if __name__ == "__main__":
    main()
