"""When run as part of a GitHub Actions workflow, this script parses a coverage report generated by pytest and posts a comment to the PR, reporting whether the coverage percentage exceeds a certain threshold."""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

import requests


def parse_coverage(xml_file: str) -> float:
    """Parses coverage from a XML file located at the provided path."""
    tree = ET.parse(xml_file)  # noqa: S314
    root = tree.getroot()
    coverage_attr = root.attrib.get("line-rate", None)
    if coverage_attr is not None:
        return float(coverage_attr) * 100
    msg = "Could not find coverage data."
    raise ValueError(msg)


def post_comment(pr_number: str, repo: str, token: str, message: str) -> None:
    """Posts a comment to the given repository and PR."""
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    response = requests.post(url, json={"body": message}, headers=headers)  # noqa: S113
    if response.status_code >= 400:  # noqa: PLR2004
        print(f"Failed to post comment: {response.text}", file=sys.stderr)


def main() -> None:  # noqa: D103
    if len(sys.argv) != 2:  # noqa: PLR2004
        print("Usage: check_coverage.py <coverage.xml>", file=sys.stderr)
        sys.exit(1)

    xml_path = sys.argv[1]
    try:
        coverage = parse_coverage(xml_path)
    except Exception as e:  # noqa: BLE001
        print(f"Error reading coverage: {e}", file=sys.stderr)
        sys.exit(1)

    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    pr_number = os.environ.get("GITHUB_PR_NUMBER")

    if not all([token, repo, pr_number]):
        print("Missing required environment variables.", file=sys.stderr)
        sys.exit(1)

    try:
        min_coverage = float(os.environ.get("MIN_CODE_COVERAGE"))
    except TypeError:
        print(
            "Missing environment variable MIN_CODE_COVERAGE or invalid format (must be float)",
            file=sys.stderr,
        )
        sys.exit(1)

    coverage_msg = (
        f"✅ Code coverage is **{coverage:.2f}%** -- OK!"
        if coverage >= min_coverage
        else f"❌ Code coverage is **{coverage:.2f}%** -- below required **{min_coverage}%**."
    )
    post_comment(pr_number, repo, token, coverage_msg)

    if coverage < min_coverage:
        sys.exit(1)


if __name__ == "__main__":
    main()
