name: Code Coverage Check

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-and-check-coverage:
    name: Check minimum coverage is satisfied

    environment:
      name: code-coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          activate-environment: true

      - name: Install required libraries
        run: |
          uv sync --only-group test

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=. --cov-report=xml

      - name: Validate coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          MIN_CODE_COVERAGE: ${{ vars.MIN_CODE_COVERAGE }}
        run: |
          python .github/scripts/coverage_comment.py coverage.xml > comment.txt

      - name: Post PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: comment.txt
